language: node_js
node_js:
  - "8"
cache: yarn
install_script:
  - yarn
script:
  - yarn generate
deploy:
  provider: pages
  local-dir: dist/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master
  target-branch: gh-pages
  committer-from-gh: true
